language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.7.1
install:
  - pip install -q coveralls
  - pip install -q beautifulsoup4
  - pip install -q Pillow
  - pip install -q Django==$DJANGO_VERSION
before_install:
  - mkdir -p test_suite/media
  - ./test_suite/install_ffmpeg.sh
script:
  cd test_suite && coverage run --source='smartfields' manage.py test && cd ..
after_success:
  coveralls
notifications:
  email:
    recipients:
      - lehins@yandex.ru
    on_success: never
    on_failure: always

