language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.7.4
  - DJANGO_VERSION=1.8a1
install:
  - pip install -q coveralls
  - pip install -q beautifulsoup4
  - pip install -q Pillow
  - pip install -q Wand
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q django-crispy-forms
before_install:
  - tests/install_ffmpeg.sh
script:
  coverage run --source='smartfields' setup.py test
after_success:
  coveralls
notifications:
  email:
    recipients:
      - lehins@yandex.ru
    on_success: never
    on_failure: always

