language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.7.6
  - DJANGO_VERSION=1.8a1
install:
  - pip install -q coveralls
  - pip install -q beautifulsoup4
  - pip install -q Pillow
  - pip install -q Wand
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q django-crispy-forms
before_install:
  - sudo apt-add-repository -y ppa:jon-severinsson/ffmpeg
  - sudo apt-get update -qq
  - sudo apt-get -y install ffmpeg
script:
  coverage run --source='smartfields' setup.py test
after_success:
  coveralls
notifications:
  email:
    recipients:
      - lehins@yandex.ru
    on_success: never
    on_failure: always
branches:
  except:
    - /^v[0-9].[0-9].[0-9]/

